name: CI

on:
  push:
    branches:
      - master

jobs:
  g8Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v5
      - name: g8Test
        run: sbt g8Test
